### ISSUE TITLE
Install does not complete on Synology Linux

### ISSUE THREAD

**Issue by gingerbeardman** [Contextualist/acp#10]
- Perhaps a way to for acp specify alternative config folder is available?

```
server% curl -fsS https://acp.deno.dev/get | sh

  ==> Using auto generated config because contextualist/acp doesn't have a bina.json file in its release
  ==> This might not work for some projects
  ==> Resolved version latest to v0.3.0
  ==> Downloading asset for linux amd64
  ==> Permissions required for installation to /usr/local/bin
Password: 
  ==> Installation complete

error writing config to /var/services/homes/admin/.config/acp/config.json: open /var/services/homes/admin/.config/acp/config.json: no such file or directory
```

afterwards I tried again
```
server% acp
Config not found. If this is your first time using acp, run `acp --setup` to generate a config
server% acp --setup
error writing config to /var/services/homes/admin/.config/acp/config.json: open /var/services/homes/admin/.config/acp/config.json: no such file or directory
```

**Comment by Contextualist** [comment]
Thanks for reporting! My first thought is that `acp` failed to create a directory at `/var/services/homes/admin/.config/acp` when trying to write to the config file. For reference, this should be the line of code that failed:

https://github.com/Contextualist/acp/blob/5fb5509f60280a85ce6babcbcdd8400b9e45e627/pkg/config/config.go#L128

The above is roughly equivalent to `mkdir -p $(dirname $configFilename) && chmod 700 $(dirname $configFilename)`.

(My bad that I did not handle error here properly) For some reason, maybe due to permission, the above operation failed. Could you double check if this is the case? Is your current user able to create directories under `/var/services/homes/admin/.config`?

**Comment by gingerbeardman** [comment]
Thanks, default user could not. 

So I went to superuser and ran the installer from there. 

That works!

**Comment by Contextualist** [comment]
Glad that this works!

It still seems unusual to me that your current user does not have write permission to its `$HOME`. Close for now, and let me know if you have further issue.
