### ISSUE TITLE
[Windows] invalid character 'i' looking for beginning of object key string

### ISSUE THREAD

**Issue by SeeFlowerX** [Contextualist/acp#3]
win下使用cmd/powershell 执行命令的时候，不管这个引号怎么改变都报这个错误

> invalid character 'i' looking for beginning of object key string

```
acp --setup-with '{"id":"***","psk":"***"}'
```

**Comment by SeeFlowerX** [comment]
改成下面的形式就可以了
```
acp --setup-with "{\"id\":\"****\",\"psk\":\"****\"}"
```

不过新的问题是，始终timeout，看起来是打洞没有成功 😢

**Comment by Contextualist** [comment]
> invalid character 'i' looking for beginning of object key string

查了一下，好像 CMD 是不支持单引号定义字符串的，然后 JSON 要求里面的字符串必须用双引号，所以必须写成后来的那种形式。PowerShell 就支持单引号定义字符串。

> 不过新的问题是，始终timeout，看起来是打洞没有成功 😢

嗯，有不少的网络环境里打洞还是比较艰难。如果可行，我还是希望能够覆盖尽可能多的网络环境。最近在尝试支持 1. 固定端口（针对只对外开放特定端口的主机）2. UPnP 端口映射（针对某些支持的（软）路由）。欢迎提议新的解决方案。

**Comment by SeeFlowerX** [comment]
我另外找过一些基于webrtc做的文件传输网站，但是无一例外都没有成功建立链接。但是只有这个ppzhilian可以正常建立链接，传输速度也还不错。

https://www.ppzhilian.com/

**Comment by Contextualist** [comment]
最近又把这个命令行报错翻出来琢磨了一下，其实应该是 CMD/PowerShell 处理引号转义的老问题了。PowerShell 7.2.0 中提出了缓解方案，详见[这个 SO 答案](https://stackoverflow.com/a/70970166)。

This error message is caused by a long-standing issue of how CMD/PowerShell is handling quotation escape, which is relieved in PowerShell 7.2.0. See [this SO answer](https://stackoverflow.com/a/70970166).
